empresa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('empresas/', views.empresas, name="empresa"),
    path('nova_empresa/', views.nova_empresa, name="nova_empresa"),
    path('excluir_empresa/<int:id>', views.excluir_empresa, name="excluir_empresa"),
    path('empresa/<int:id>', views.empresa, name="empresa_unica"),

]

seletive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('empresa.urls')),
    path('vagas/', include('vagas.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vagas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('nova_vaga/', views.nova_vaga, name="nova_vaga"),
    path('vaga/<int:id>', views.vaga, name="vaga"),
    path('nova_tarefa/<int:id_vaga>', views.nova_tarefa, name='nova_tarefa'),
    path('realizar_tarefa/<int:id>', views.realizar_tarefa, name='realizar_tarefa'),
    path('envia_email/<int:id_vaga>', views.envia_email, name="envia_email"),
]

empresa/models.py
from django.db import models

# Create your models here.


class Tecnologias(models.Model):
    tecnologia = models.CharField(max_length=30)

    def __str__(self):
        return self.tecnologia


class Empresa(models.Model):
    choices_nicho_mercado = (
        ('M', 'Marketing'),
        ('N', 'Nutrição'),
        ('D', 'Design')
    )
    logo = models.ImageField(upload_to="logo_empresa")
    nome = models.CharField(max_length=30)
    email = models.EmailField()
    cidade = models.CharField(max_length=30)
    tecnologias = models.ManyToManyField(Tecnologias)
    endereco = models.CharField(max_length=60)
    nicho_mercado = models.CharField(
        max_length=3, choices=choices_nicho_mercado)
    caracteristica_empresa = models.TextField()

    def __str__(self) -> str:
        return self.nome

    def qtd_vagas(self):
        return Vagas.objects.filter(empresa__id=self.id).count()


class Vagas(models.Model):
    choices_experiencia = (
        ('J', 'Júnior'),
        ('P', 'Pleno'),
        ('S', 'Sênior')
    )

    choices_status = (
        ('I', 'Interesse'),
        ('C', 'Currículo enviado'),
        ('E', 'Entrevista'),
        ('D', 'Desafio técnico'),
        ('F', 'Finalizado')
    )

    empresa = models.ForeignKey(Empresa, null=True, on_delete=models.SET_NULL)
    titulo = models.CharField(max_length=30)
    email = models.EmailField(null=True)
    nivel_experiencia = models.CharField(
        max_length=2, choices=choices_experiencia)
    data_final = models.DateField()
    status = models.CharField(max_length=30, choices=choices_status)
    tecnologias_dominadas = models.ManyToManyField(Tecnologias)
    tecnologias_estudar = models.ManyToManyField(
        Tecnologias, related_name='estudar')

    def __str__(self):
        return self.titulo

    def progresso(self):
        x = [((i+1)*20, j[0]) for i, j in enumerate(self.choices_status)]
        x = list(filter(lambda x: x[1] == self.status, x))[0][0]
        return x

empresa/views.py
from django.contrib import messages
from django.contrib.messages import constants
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Tecnologias, Empresa, Vagas


def nova_empresa(request):
    if request.method == "GET":
        techs = Tecnologias.objects.all()
        return render(request, 'nova_empresa.html', {'techs': techs})
    elif request.method == "POST":
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        cidade = request.POST.get('cidade')
        endereco = request.POST.get('endereco')
        nicho = request.POST.get('nicho')
        caracteristicas = request.POST.get('caracteristicas')
        tecnologias = request.POST.getlist('tecnologias')
        logo = request.FILES.get('logo')

        if (len(nome.strip()) == 0 or len(email.strip()) == 0 or len(cidade.strip()) == 0 or len(endereco.strip()) == 0 or len(nicho.strip()) == 0 or len(caracteristicas.strip()) == 0 or (not logo)):
            messages.add_message(request, constants.ERROR,
                                 'Preencha todos os campos')
            return redirect('/home/nova_empresa')

        if logo.size > 100_000_000:
            messages.add_message(request, constants.ERROR,
                                 'A logo da empresa deve ter menos de 10MB')
            return redirect('/home/nova_empresa')

        if nicho not in [i[0] for i in Empresa.choices_nicho_mercado]:
            messages.add_message(request, constants.ERROR,
                                 'Nicho de mercado inválido')
            return redirect('/home/nova_empresa')

        empresa = Empresa(logo=logo,
                          nome=nome,
                          email=email,
                          cidade=cidade,
                          endereco=endereco,
                          nicho_mercado=nicho,
                          caracteristica_empresa=caracteristicas)
        empresa.save()
        empresa.tecnologias.add(*tecnologias)
        empresa.save()
        messages.add_message(request, constants.SUCCESS,
                             'Empresa cadastrada com sucesso')
        return redirect('/home/empresas')


def empresas(request):
    technologias_filtrar = request.GET.get('tecnologias')
    nome_filtrar = request.GET.get('nome')
    empresas = Empresa.objects.all()

    if technologias_filtrar:
        empresas = empresas.filter(tecnologias=technologias_filtrar)

    if nome_filtrar:
        empresas = empresas.filter(nome__icontains=nome_filtrar)

    tecnologias = Tecnologias.objects.all()
    return render(request, 'empresas.html', {'empresas': empresas, 'tecnologias': tecnologias})


def excluir_empresa(request, id):
    empresa = Empresa.objects.get(id=id)
    empresa.delete()
    messages.add_message(request, constants.SUCCESS,
                         'Empresa excluída com sucesso')
    return redirect('/home/empresas')


def empresa(request, id):
    empresa = get_object_or_404(Empresa, id=id)
    empresas = Empresa.objects.all()
    tecnologias = Tecnologias.objects.all()
    vagas = Vagas.objects.filter(empresa_id=id)
    return render(request, 'empresa.html', {'empresa': empresa,
                                            'tecnologias': tecnologias,
                                            'empresas': empresas,
                                            'vagas': vagas})

empresa/templates/empresa.html
{% extends 'base.html' %} {% load static %} {% block 'head' %}
<link href="{% static 'empresa/css/empresa.css' %}" rel="stylesheet" />
{% endblock%} {% block 'body' %}

<br />
<div class="container">
  {% if messages %} {% for message in messages %}
  <br />
  <section class="alert {{message.tags}}">{{message}}</section>
  {% endfor %} {% endif %}
  <div class="row">
    <div class="col-md-3">
      <img width="100%" src="{{empresa.logo.url}}" />
    </div>

    <div class="col-md">
      <h1 class="titulo">{{empresa.nome}}</h1>
      <p class="paragrafo">{{empresa.endereco}}</p>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-md-6">
      <label>Nicho de mercado:</label>
      <input
        disabled
        type="text"
        class="form-control"
        value="{{empresa.get_nicho_mercado_display}}"
      />
    </div>

    <div class="col-md-3">
      <label>Tecnologias usadas:</label>
      <select class="form-select">
        {% for tech in empresa.tecnologias.all %}
        <option>{{tech}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-md-7">
      <label>Características da empresa:</label>
      <textarea disabled class="form-control">
{{empresa.caracteristica_empresa}}</textarea
      >
    </div>

    <div class="col-md-3"></div>
  </div>

  <hr />

  <a
    data-bs-toggle="modal"
    data-bs-target="#exampleModal"
    class="btn btn-lg btn-orange"
    >Nova vaga</a
  >

  <div class="row">
    {% for vaga in vagas %}
      <div class="col-md">
        <div class="box-vagas">
          <div class="header-vagas">
              <a class="btn-titulo-vagas" href="{% url 'vaga' vaga.id %}">
                {{vaga.titulo}}
              </a>
          </div>
          <div class="body-vagas">
            <div class="row">
              <div class="col-md">
                <label class="paragrafo">Nível:</label>
                <br>        
                <label class="paragrafo paragrafo-orange">{{vaga.get_nivel_experiencia_display}}</label>                           
              </div>
              <div class="col-md">
                <label class="paragrafo">Status <img src="{% static 'empresa/img/flag_green.png' %}"></label>
                <br>        
                <label class="paragrafo paragrafo-orange">{{vaga.get_status_display}}</label>                           
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
<br />
<br />
<div
  class="modal fade modal-lg"
  id="exampleModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5
          style="font-size: 30px"
          class="modal-title titulo"
          id="exampleModalLabel"
        >
          Nova vaga
        </h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form action="{% url 'nova_vaga' %}" method="POST">{% csrf_token %}
          <div class="row">
            <div class="col-md">
              <label>Título:</label>
              <input
                type="text"
                name="titulo"
                class="form-control"
                placeholder="Digite o título da vaga..."
              />
            </div>

            <div class="col-md">
              <label>Email:</label>
              <input
                type="email"
                name="email"
                class="form-control"
                placeholder="email@email.com.br"
              />
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-md">
              <label>Tecnologias que já domino:</label>
              <select name="tecnologias_domina" class="form-select" multiple>
                {% for tech in tecnologias %}
                <option value="{{tech.id}}">{{tech}}</option>
                {% endfor %}
              </select>
            </div>

            <div class="col-md">
              <label>Tecnologias que não domino:</label>
              <select
                name="tecnologias_nao_domina"
                class="form-select"
                multiple
              >
                {% for tech in tecnologias %}
                <option value="{{tech.id}}">{{tech}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-md">
              <label>Nível de experiência:</label>
              <select name="experiencia" class="form-select">
                <option value="J">Júnior</option>
                <option value="P">Pleno</option>
                <option value="S">Sênior</option>
              </select>
            </div>

            <div class="col-md">
              <label>Data final:</label>
              <input type="date" class="form-control" name="data_final" />
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-md">
              <label>Empresa:</label>
              <select name="empresa" class="form-select">
                {% for empresa_iter in empresas %}
                <option {% if empresa_iter.id == empresa.id %}selected{% endif %} value="{{empresa_iter.id}}">{{empresa_iter}}</option>
                {% endfor %}
              </select>
            </div>
          </div>

          <br />
          <div class="row">
            <div class="col-md">
              <label>Status:</label>
              <select name="status" class="form-select">
                <option value="I">Interesse</option>
                <option value="C">Currículo enviado</option>
                <option value="E">Entrevista</option>
                <option value="D">Desafio técnico</option>
                <option value="F">Finalizado</option>
              </select>
            </div>
          </div>
          <br />
          <input
            type="submit"
            value="Nova vaga"
            class="btn btn-lg btn-orange"
          />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

empresa/templates/empresas.html
{% extends 'base.html' %} {% load static %} {% load filtro %} {% block 'head' %}
<link href="{% static 'empresa/css/empresas.css' %}" rel="stylesheet" />
{% endblock%} {% block 'body' %}
<div class="wrapper">
  <div class="box">
    <div class="header-box">
      {% if messages %} {% for message in messages %}
      <section class="alert {{message.tags}}">{{message}}</section>
      {% endfor %} {% endif %}
      <h2 class="titulo">Gerenciar empresas</h2>
      <a class="btn-nova-empresa" href="{% url 'nova_empresa' %}"
        >Nova empresa</a
      >
    </div>
    <div class="borda-box"></div>
    <div class="body-box">
      <form action="{% url 'empresa' %}" method="GET">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-5">
            <input
              type="text"
              placeholder="Busque pelo nome"
              class="form-control"
              name="nome"
            />
          </div>
          <div class="col-md-4">
            <select class="form-select" name="tecnologias">
              <option value="">Filtre pela Tecnologia</option>
              {% for tech in tecnologias%}
              <option value="{{tech.id}}">{{tech}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="col-md-3">
            <input
              type="submit"
              value="FILTRAR"
              class="btn btn-lg btn-orange"
            />
          </div>
        </div>
      </form>

      <table class="tabela" cellpadding="20">
        <tr>
          <th>Nome</th>
          <th>Endereço</th>
          <th>Tecnologias usadas</th>
          <th>Quantidade de vagas</th>
          <th>Ação</th>
        </tr>
        {% if not empresas %}
        <tr>
          <td colspan="5" class="tabela-linha">
            <p>Não existem Empresas cadastradas</p>
          </td>
        </tr>
        {% endif %} {% for empresa in empresas%}
        <tr {% if forloop.counter|is_par %} class="tabela-linha" {% endif %}>
          <td>
            <a
              class="btn-nome-empresas"
              href="{% url 'empresa_unica' empresa.id %}"
              >{{empresa.nome}}</a
            >
          </td>
          <td>{{empresa.endereco}}</td>
          <td>
            <select class="form-select">
              {% for tech in empresa.tecnologias.all %}
              <option>{{tech}}</option>
              {% endfor %}
              <option></option>
            </select>
          </td>
          <td>
            {% if empresa.qtd_vagas > 0 %}
            <img src="{% static 'empresa/img/flag_green.png' %}" />
            {% else %}
            <img src="{% static 'empresa/img/flag_red.png' %}" />
            {% endif %} &nbsp&nbsp{{empresa.qtd_vagas}}
          </td>
          <td>
            <a class="btn-excluir" href="{% url 'excluir_empresa' empresa.id %}"
              >Excluir empresa</a
            >
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>
{% endblock%}

empresa/templates/nova_empresa.html
{% extends "base.html" %} {% load static %} {% block 'head' %}
<link href="{% static 'empresa/css/nova_empresa.css' %}" rel="stylesheet" />
{% endblock%} {% block 'body' %}
<div class="wrapper">
  <div class="box">
    <div class="header">
      <h3 class="titulo">Nova empresa</h3>
    </div>
    {% if messages %} {% for message in messages %}
    <br />
    <section class="alert {{message.tags}}">{{message}}</section>
    {% endfor %} {% endif %}
    <div class="body-box">
      <form
        action="{% url 'nova_empresa' %}"
        method="POST"
        enctype="multipart/form-data"
      >
        {% csrf_token %}
        <div class="row">
          <div class="col-md">
            <label>Nome:</label>
            <input
              type="text"
              class="form-control"
              name="nome"
              placeholder="Digite seu nome..."
            />
          </div>

          <div class="col-md">
            <label>E-mail:</label>
            <input
              type="email"
              class="form-control"
              name="email"
              placeholder="email@gmail.com"
            />
          </div>
        </div>
        <br />
        <div class="row">
          <div class="col-md">
            <label>Cidade:</label>
            <input
              type="text"
              class="form-control"
              name="cidade"
              placeholder="Digite a cidade da empresa..."
            />
          </div>

          <div class="col-md">
            <label>Endereço:</label>
            <input
              type="text"
              class="form-control"
              name="endereco"
              placeholder="Rua..."
            />
          </div>
        </div>
        <br />
        <div class="row">
          <div class="col-md">
            <label>Nicho de mercado:</label>
            <select class="form-control" name="nicho">
              <option value="M">Marketing</option>
              <option value="N">Nutrição</option>
              <option value="D">Design</option>
            </select>
          </div>
        </div>
        <br />
        <div class="row">
          <div class="col-md">
            <label>Tecnologias usadas:</label>
            <select class="form-control" name="tecnologias" multiple>
              {% for tech in techs %}
              <option value="{{tech.id}}">{{tech.tecnologia}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <br />
        <div class="row">
          <div class="col-md">
            <label>Característica da empresa:</label>
            <textarea name="caracteristicas" class="form-control"></textarea>
          </div>
        </div>
        <br />
        <div class="row">
          <div class="col-md">
            <label>Logo:</label>
            <input type="file" class="form-control" name="logo" />
          </div>
        </div>
        <br />
        <input
          type="submit"
          value="Nova empresa"
          class="btn btn-lg btn-orange"
        />
        <a class="btn-empresas" href="{% url 'empresa' %}">Empresas</a>
      </form>
    </div>
  </div>
</div>
{% endblock%}