seletive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('empresa.urls')),
    path('vagas/', include('vagas.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vagas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('nova_vaga/', views.nova_vaga, name="nova_vaga"),
    path('vaga/<int:id>', views.vaga, name="vaga"),
    path('nova_tarefa/<int:id_vaga>', views.nova_tarefa, name='nova_tarefa'),
    path('realizar_tarefa/<int:id>', views.realizar_tarefa, name='realizar_tarefa'),
    path('envia_email/<int:id_vaga>', views.envia_email, name="envia_email"),
]

empresa/models.py
from django.db import models

# Create your models here.


class Tecnologias(models.Model):
    tecnologia = models.CharField(max_length=30)

    def __str__(self):
        return self.tecnologia


class Empresa(models.Model):
    choices_nicho_mercado = (
        ('M', 'Marketing'),
        ('N', 'Nutrição'),
        ('D', 'Design')
    )
    logo = models.ImageField(upload_to="logo_empresa")
    nome = models.CharField(max_length=30)
    email = models.EmailField()
    cidade = models.CharField(max_length=30)
    tecnologias = models.ManyToManyField(Tecnologias)
    endereco = models.CharField(max_length=60)
    nicho_mercado = models.CharField(
        max_length=3, choices=choices_nicho_mercado)
    caracteristica_empresa = models.TextField()

    def __str__(self) -> str:
        return self.nome

    def qtd_vagas(self):
        return Vagas.objects.filter(empresa__id=self.id).count()


class Vagas(models.Model):
    choices_experiencia = (
        ('J', 'Júnior'),
        ('P', 'Pleno'),
        ('S', 'Sênior')
    )

    choices_status = (
        ('I', 'Interesse'),
        ('C', 'Currículo enviado'),
        ('E', 'Entrevista'),
        ('D', 'Desafio técnico'),
        ('F', 'Finalizado')
    )

    empresa = models.ForeignKey(Empresa, null=True, on_delete=models.SET_NULL)
    titulo = models.CharField(max_length=30)
    email = models.EmailField(null=True)
    nivel_experiencia = models.CharField(
        max_length=2, choices=choices_experiencia)
    data_final = models.DateField()
    status = models.CharField(max_length=30, choices=choices_status)
    tecnologias_dominadas = models.ManyToManyField(Tecnologias)
    tecnologias_estudar = models.ManyToManyField(
        Tecnologias, related_name='estudar')

    def __str__(self):
        return self.titulo

    def progresso(self):
        x = [((i+1)*20, j[0]) for i, j in enumerate(self.choices_status)]
        x = list(filter(lambda x: x[1] == self.status, x))[0][0]
        return x

vagas/models.py
from django.db import models
from empresa.models import Vagas
from django.utils.safestring import mark_safe

# Create your models here.


class Tarefa(models.Model):
    choices_prioridade = (
        ('B', 'Baixa'),
        ('A', 'Alta'),
        ('U', 'Urgente')
    )
    vaga = models.ForeignKey(Vagas, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=30)
    prioridade = models.CharField(max_length=1, choices=choices_prioridade)
    data = models.DateField()
    realizada = models.BooleanField(default=False)

    def __str__(self):
        return self.titulo

    def icon(self):
        if self.prioridade == "U":
            classe = 'prioridade-vermelho'
        elif self.prioridade == "A":
            classe = 'prioridade-amarelo'
        elif self.prioridade == "B":
            classe = 'prioridade-verde'

        icon = f'''<svg  class="{classe}" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
                                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                    </svg>'''
        return mark_safe(icon)


class Emails(models.Model):
    vaga = models.ForeignKey(Vagas, on_delete=models.DO_NOTHING)
    assunto = models.CharField(max_length=100)
    corpo = models.TextField()
    enviado = models.BooleanField()

    def __str__(self):
        return self.assunto

vagas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.contrib import messages
from django.contrib.messages import constants
from empresa.models import Vagas
from .models import Tarefa, Emails
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import EmailMultiAlternatives
from django.conf import settings

# Create your views here.


def nova_vaga(request):
    if request.method == "POST":
        titulo = request.POST.get('titulo')
        email = request.POST.get('email')
        tecnologias_domina = request.POST.getlist('tecnologias_domina')
        tecnologias_nao_domina = request.POST.getlist('tecnologias_nao_domina')
        experiencia = request.POST.get('experiencia')
        data_final = request.POST.get('data_final')
        empresa = request.POST.get('empresa')
        status = request.POST.get('status')

        # TODO: validations

        vaga = Vagas(
            titulo=titulo,
            email=email,
            nivel_experiencia=experiencia,
            data_final=data_final,
            empresa_id=empresa,
            status=status,
        )

        vaga.save()

        vaga.tecnologias_estudar.add(*tecnologias_nao_domina)
        vaga.tecnologias_dominadas.add(*tecnologias_domina)

        vaga.save()
        messages.add_message(request, constants.SUCCESS,
                             'Vaga criada com sucesso.')
        return redirect(f'/home/empresa/{empresa}')
    elif request.method == "GET":
        raise Http404()


def vaga(request, id):
    vaga = get_object_or_404(Vagas, id=id)
    tarefas = Tarefa.objects.filter(vaga=vaga).filter(realizada=False)
    emails = Emails.objects.filter(vaga=vaga)
    return render(request, 'vaga.html', {'vaga': vaga,
                                         'tarefas': tarefas,
                                         'emails': emails, })


def nova_tarefa(request, id_vaga):
    titulo = request.POST.get('titulo')
    prioridade = request.POST.get("prioridade")
    data = request.POST.get('data')

    # TODO: validations
    try:
        tarefa = Tarefa(vaga_id=id_vaga,
                        titulo=titulo,
                        prioridade=prioridade,
                        data=data)
        tarefa.save()
        messages.add_message(request, constants.SUCCESS,
                             'Tarefa criada com sucesso')
    except:
        messages.add_message(request, constants.ERROR,
                             'Erro interno do Sistema')
    return redirect(f'/vagas/vaga/{id_vaga}')


def realizar_tarefa(request, id):
    tarefas_list = Tarefa.objects.filter(id=id).filter(realizada=False)

    if not tarefas_list.exists():
        messages.add_message(request, constants.ERROR,
                             'Erro interno do sistema!')
        return redirect(f'/home/empresas/')

    tarefa = tarefas_list.first()
    tarefa.realizada = True
    tarefa.save()
    messages.add_message(request, constants.SUCCESS,
                         'Tarefa realizada com sucesso, parabéns!')
    return redirect(f'/vagas/vaga/{tarefa.vaga.id}')


def envia_email(request, id_vaga):
    vaga = Vagas.objects.get(id=id_vaga)
    assunto = request.POST.get('assunto')
    corpo = request.POST.get('corpo')

    html_content = render_to_string(
        'emails/template_email.html', {'corpo': corpo})
    text_content = strip_tags(html_content)
    email = EmailMultiAlternatives(
        assunto, text_content, settings.EMAIL_HOST_USER, [vaga.email, ])
    email.attach_alternative(html_content, "text/html")
    if email.send():
        mail = Emails(
            vaga=vaga,
            assunto=assunto,
            corpo=corpo,
            enviado=True
        )
        mail.save()
        messages.add_message(request, constants.SUCCESS,
                             'Email enviado com sucesso.')
    else:
        mail = Emails(
            vaga=vaga,
            assunto=assunto,
            corpo=corpo,
            enviado=False
        )
        mail.save()
        messages.add_message(request, constants.ERROR,
                             'Erro interno do sistema! Email não foi enviado!')
    return redirect(f'/vagas/vaga/{id_vaga}')

vagas/templates/vaga.html
{% extends 'base.html' %} {% load static %} {% block 'head' %}
<link rel="stylesheet" href="{% static 'vaga/css/vaga.css' %}" />
{% endblock %} {% block 'body' %}
<div class="container">
  {% if messages %} {% for message in messages %}
  <br />
  <section class="alert {{message.tags}}">{{message}}</section>
  {% endfor %} {% endif %}
  <br />
  <h3 class="titulo">{{vaga.titulo}}</h3>
  <p class="titulo2">{{vaga.empresa}}</p>
  <p>Progresso atual - {{vaga.get_status_display}}</p>

  <div style="width: 40%" class="progress">
    <div
      class="progress-bar progress-bar-striped bg-success"
      role="progressbar"
      style="width: {{vaga.progresso}}%"
      aria-valuenow="25"
      aria-valuemin="0"
      aria-valuemax="100"
    ></div>
  </div>
</div>

<div class="bg2">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <p class="titulo2">Crie uma tarefa</p>
        <p>Lembre-se de realizar todas suas tarefas com antecedência</p>

        <form action="{% url 'nova_tarefa' vaga.id %}" method="POST">
          {% csrf_token %}
          <label>Título:</label>
          <input
            name="titulo"
            type="text"
            class="form-control input-tarefa"
            placeholder="Digite o título da tarefa..."
          />
          <br />
          <label>Prioridade:</label>
          <select name="prioridade" class="form-select input-tarefa">
            <option value="U">Urgente</option>
            <option value="A">Alta</option>
            <option value="B">Baixa</option>
          </select>
          <br />
          <label>Data:</label>
          <input
            name="data"
            type="date"
            class="form-control input-tarefa"
            placeholder=""
          />
          <br />
          <input type="submit" value="Nova tarefa" class="btn btn-orange" />
        </form>
      </div>
      <div class="col-md">
        {% for tarefa in tarefas %}
        <div class="li-tarefa">
          <label>{{tarefa.titulo}}</label>
          <label class="prioridade-bloco">
            {{tarefa.icon}} {{tarefa.get_prioridade_display}}
          </label>
          <label class="prioridade-bloco"> {{tarefa.data}} </label>
          <label class="prioridade-bloco">
            <a
              href="{% url 'realizar_tarefa' tarefa.id %}"
              class="btn btn-success"
              >Finalizado</a
            >
          </label>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<div class="container bg3">
  <div class="row">
    <div class="col-md">
      <p class="titulo2">Enviar E-mail</p>
      <p>Envie e-mails para essa vaga por aqui.</p>
    </div>

    <div class="col-md">
      <form action="{% url 'envia_email' vaga.id%}" method="POST">
        {% csrf_token %}
        <label>Assunto:</label>
        <input
          name="assunto"
          type="text"
          class="form-control"
          placeholder="assunto"
        />
        <br />
        <label>Corpo do email:</label>
        <textarea name="corpo" class="form-control"></textarea>
        <br />
        <input type="submit" class="btn btn-orange" value="Enviar" />
      </form>
    </div>
  </div>
</div>

<div class="bg2">
  <div class="container">
    <div class="row">
      <h3 class="titulo">Histórico de e-mails</h3>
      {% if not emails %}
      <div class="col-md">
        <div class="box-email">
          <div class="header-email">Nenhum email enviado até o momento!</div>
        </div>
      </div>
      {% endif %} {% for email in emails%}
      <div class="col-md">
        <div class="box-email">
          <div class="header-email">
            {% if email.enviado %}
            <img
              alt="Enviado com sucesso!"
              title="Enviado com sucesso!"
              src="{% static 'empresa/img/flag_green.png' %}"
            />
            {% else %}
            <img
              alt="Falha no envio!"
              title="Falha no envio!"
              src="{% static 'empresa/img/flag_red.png' %}"
            />
            {% endif %} &nbsp&nbsp{{empresa.qtd_vagas}} {{email.assunto}}
          </div>
          <div class="body-email">{{email.corpo}}</div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="container bg3">
  <div class="row">
    <div class="col-md">
      <p class="titulo2">Tecnologias que domino</p>

      <div class="li-tech">
        Python

        <svg
          class="arrow-right"
          xmlns="http://www.w3.org/2000/svg"
          width="26"
          height="26"
          fill="currentColor"
          class="bi bi-arrow-right"
          viewBox="0 0 16 16"
        >
          <path
            fill-rule="evenodd"
            d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"
          />
        </svg>
      </div>
    </div>

    <div class="col-md">
      <p class="titulo2">Preciso estudar</p>

      <div class="li-tech">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="26"
          height="26"
          fill="currentColor"
          class="bi bi-arrow-left"
          viewBox="0 0 16 16"
        >
          <path
            fill-rule="evenodd"
            d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"
          />
        </svg>
        Python
      </div>
    </div>
  </div>
</div>
{% endblock %}